export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';


export const ADD_DEVICE_REQUEST = 'ADD_DEVICE_REQUEST';
export const ADD_DEVICE_SUCCESS = 'ADD_DEVICE_SUCCESS';
export const ADD_DEVICE_FAILURE = 'ADD_DEVICE_FAILURE';

export const BOOK_DEVICE_REQUEST = 'BOOK_DEVICE_REQUEST';
export const BOOK_DEVICE_SUCCESS = 'BOOK_DEVICE_SUCCESS';
export const BOOK_DEVICE_FAILURE = 'BOOK_DEVICE_FAILURE';

export const EDIT_DEVICE_REQUEST = 'EDIT_DEVICE_REQUEST';
export const EDIT_DEVICE_SUCCESS = 'EDIT_DEVICE_SUCCESS';
export const EDIT_DEVICE_FAILURE = 'EDIT_DEVICE_FAILURE';

export const BOOKING_HISTORY_REQUEST = 'BOOKING_HISTORY_REQUEST';
export const BOOKING_HISTORY_SUCCESS = 'BOOKING_HISTORY_SUCCESS';
export const BOOKING_HISTORY_FAILURE = 'BOOKING_HISTORY_FAILURE';

export const DEVICE_REQUEST_SUCCESS = 'DEVICE_REQUEST_SUCCESS';
export const HISTORY_REQUEST_SUCCESS = 'HISTORY_REQUEST_SUCCESS';

export const DELETE_DEVICE_REQUEST = 'DELETE_DEVICE_REQUEST';
export const DELETE_DEVICE_SUCCESS = 'DELETE_DEVICE_SUCCESS';
export const DELETE_DEVICE_FAILURE = 'DELETE_DEVICE_FAILURE';

export const RELEASE_DEVICE_REQUEST = 'RELEASE_DEVICE_REQUEST';
export const RELEASE_DEVICE_SUCCESS = 'RELEASE_DEVICE_SUCCESS';
export const RELEASE_DEVICE_FAILURE = 'RELEASE_DEVICE_FAILURE';